chore: wallpaper module
Currently throwing this kinda stuff

Installing Lanzaboote to "/boot"...
Collecting garbage...
Successfully installed Lanzaboote.
activating the configuration...
sops-install-secrets: Imported /etc/ssh/ssh_host_rsa_key as GPG key with fingerprint 742f98c122b7177b97d2a19cc5de1c0228abbd26
sops-install-secrets: Imported /etc/ssh/ssh_host_ed25519_key as age key with fingerprint age19pyh5fyjt2t0c9n9q8famqj6yfe2cnfaulzj336a9e7tfzkqrfjs7vl702
setting up /etc...
Generating pie chart wallpaper from user wallpapers...
Generating combined wallpaper with 2560x1440 dimensions
Error: Input file does not exist: Found wallpaper for user squeals: /home/squeals/.config/stylix/image
Activation script snippet 'generatePieChartWallpaper' failed (1)
Failed to run activate script
reloading user units for dio...
restarting sysinit-reactivation.target
the following new units were started: NetworkManager-dispatcher.service
warning: the following units failed: grafana-alloy.service
● grafana-alloy.service - Grafana Alloy for laptop metrics
     Loaded: loaded (/etc/systemd/system/grafana-alloy.service; enabled; preset: ignored)
     Active: active (running) since Sun 2025-06-22 17:31:04 CEST; 7ms ago
 Invocation: bd1689d51d344e67a556f7716874d721
   Main PID: 105521 (16)
         IP: 0B in, 0B out
         IO: 0B read, 0B written
      Tasks: 1 (limit: 9216)
     Memory: 516K (peak: 516K)
        CPU: 1ms
     CGroup: /system.slice/grafana-alloy.service
             └─105521 /nix/store/if9z6wmzmb07j63c02mvfkhn1mw1w5p4-systemd-257.5/lib/systemd/systemd-executor --deserialize 424 --log-level info --log-target journal-or-kmsg

Jun 22 17:31:04 shulkerbox systemd[1]: grafana-alloy.service: Scheduled restart job, restart counter is at 4.
Jun 22 17:31:04 shulkerbox systemd[1]: Started Grafana Alloy for laptop metrics.
warning: error(s) occurred while switching to the new configuration

Signed-off-by: Vincent Palmer <shift@someone.section.me>